//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacturing_Execution.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2016")]
        public global::DevComponents.DotNetBar.eStyle menuStrip1 {
            get {
                return ((global::DevComponents.DotNetBar.eStyle)(this["menuStrip1"]));
            }
            set {
                this["menuStrip1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OfficeMobile2014")]
        public global::DevComponents.DotNetBar.eStyle metroShell10 {
            get {
                return ((global::DevComponents.DotNetBar.eStyle)(this["metroShell10"]));
            }
            set {
                this["metroShell10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2016")]
        public global::DevComponents.DotNetBar.eStyle metroShellmain {
            get {
                return ((global::DevComponents.DotNetBar.eStyle)(this["metroShellmain"]));
            }
            set {
                this["metroShellmain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2016")]
        public global::DevComponents.DotNetBar.eStyle metroShellpb {
            get {
                return ((global::DevComponents.DotNetBar.eStyle)(this["metroShellpb"]));
            }
            set {
                this["metroShellpb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VisualStudio2012Dark")]
        public global::DevComponents.DotNetBar.eStyle panelEx1 {
            get {
                return ((global::DevComponents.DotNetBar.eStyle)(this["panelEx1"]));
            }
            set {
                this["panelEx1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VisualStudio2012Dark")]
        public global::DevComponents.DotNetBar.eStyle metroStatusBar2 {
            get {
                return ((global::DevComponents.DotNetBar.eStyle)(this["metroStatusBar2"]));
            }
            set {
                this["metroStatusBar2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VisualStudio2012Dark")]
        public global::DevComponents.DotNetBar.eStyle metroStatusBar3 {
            get {
                return ((global::DevComponents.DotNetBar.eStyle)(this["metroStatusBar3"]));
            }
            set {
                this["metroStatusBar3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2016")]
        public global::DevComponents.DotNetBar.eStyle metroStatusBar4 {
            get {
                return ((global::DevComponents.DotNetBar.eStyle)(this["metroStatusBar4"]));
            }
            set {
                this["metroStatusBar4"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=EMS;Persist Security Info=True;User ID=sa;Password=" +
            "123")]
        public string EMSConnectionString {
            get {
                return ((string)(this["EMSConnectionString"]));
            }
        }
    }
}
